module XeroEngine
  require 'devise'
  require 'high_voltage'
  require 'stripe-rails'
  require 'xeroizer'
  require 'jquery-rails'
  require 'money-rails'
  require 'rack/timeout'
  require 'redis'
  require 'sinatra'
  require 'sidekiq'
  require 'sidekiq_mailer'
  require 'pundit'
  require 'flutie'
  require 'simple_form'
  require 'bootstrap-sass'
  require 'xero_engine/engine'
end