default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  xero_consumer_key: <%= ENV["XERO_CONSUMER_KEY"] %>
  xero_consumer_secret: <%= ENV["XERO_CONSUMER_SECRET"] %>
  stripe_secret: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_public: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  sidekiq_password: <%= ENV['SIDEKIQ_MONITORING_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
